### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated.

### ISSUE THREAD

**Issue by OndraRehounek** [pimlie/nuxt-rfg-icon#12]
Getting this warning with each build, app works great though

`DeprecationWarning: Tapable.plugin is deprecated. Use new API on .hooks instead `

Node version: 10.15.2
npm version: 6.4.1

Thank you very much for this app!

**Comment by pimlie** [comment]
Thanks for the report. This is an upstream issue in the nuxt meta/pwa module. See here: https://github.com/nuxt-community/pwa-module/issues/120

**Comment by OndraRehounek** [comment]
Oh I see, I am very sorry, thank you for your time and such must reply
