### ISSUE TITLE
Stray quote in generated tags when using the versioning configuration

### ISSUE THREAD

**Issue by spocock** [pimlie/nuxt-rfg-icon#14]
With the `versioning` option set in config

````
        "versioning": {
          "paramName": "v",
          "paramValue": "ngJgm6pMvR"
        }
````

the generated items are badly quoted with a stray " after the `v= ` e.g. within

````
<meta data-n-head="true" name="msapplication-TileImage" content="/favicons/mstile-144x144.png?v="ngJgm6pMvR"><meta data-n-head="true" name="msapplication-config" content="/favicons/browserconfig.xml?v="ngJgm6pMvR">
:
:
<link data-n-head="true" rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png?v="ngJgm6pMvR">
````

see 

````
"/favicons/mstile-144x144.png?v="ngJgm6pMvR"
````

**Comment by pimlie** [comment]
Who says you cant parse html with a regex? Well, a lot of people actually and a faulty regex was exactly what was causing this issue. Changed the regex to be less general as we know exactly what the html looks like we get from the rfg api. Should be fixed in 0.6.4, thanks for the report :)
