### ISSUE TITLE
`router.base` based path `staticPath` case

### ISSUE THREAD

**Issue by serialine** [pimlie/nuxt-rfg-icon#9]
**nuxt.config.js**
```javascript
const PROXY_PATH = '/front'
// (...)

modules: [
    [
      'nuxt-rfg-icon',
      {
        staticPath: PROXY_PATH + '/icons/',
        rfg: faviconDescription,
      },
    ],
],

router: {
    base: `${PROXY_PATH}`,
},
```

**What i expected:**
- Case 1. 
```javascript
staticPath: `/icons/`
```

- [X] 1. generated filesystem icon path is: `static/icons/`
- [ ] 2. compiled `headers.json`, `manifest.json` like ...
```json
"src": "/{router.base}/icons/android-chrome-192x192.png"
```
generated =>  `"src": "/icons/android-chrome-192x192.png"`
---

- Case 2. 
```javascript
staticPath: `/${router.base}/icons/`
```

- [ ] 1. generated filesystem icon path is: `static/icons/` 
=> generated: `static/front/icons/`
- [X] 2. compiled `headers.json`, `manifest.json` like ...
```
"src": "/{router.base}/icons/android-chrome-192x192.png"
```
- [X] 3. nuxt server static icon serve path is..
```
http://localhost/{router.base}/icons/android-chrome-192x192.png
...

```

---

**Description**

I am running nuxt server as reversed proxy on subdirectory path `/front`. this path is root of nuxt.
so, I set my nuxt.config to `router.base = '/front'`
therefore my nuxt server static path `/` is heading to `/front/`.

When I build nuxt-rfg-icon favicon built with above option is `static: true`.
so module work runs like below
```javascript
let publicPath = faviconConfig.staticPath
if (publicPath.charAt(0) !== '/') publicPath = '/' + publicPath
if (publicPath.charAt(publicPath.length - 1) !== '/') publicPath += '/'

faviconConfig.rfg.iconsPath = fixUrl(publicPath) // => '/front/icons/'
```

but then, generated icon files placed the path: `static/front/icons`
so it actually serving path `http://localhost/front/front/icons/`.

is my config way is wrong?

**Comment by pimlie** [comment]
First of all, sorry it took so long to respond. Totally missed this issue :confused: 
Secondly, thanks for the very informative report.

I think the issue here is that this module doesnt account for router.base in static mode while it should. Pleaes try the latest version and let me know if it works!

**Comment by pimlie** [comment]
Please reopen if you have an update on this

**Comment by mmoollllee** [comment]
Hey! I serve an example of a template via gh-pages. Therefore I need this too, but it still doesn't account for router.base setting.
See the repo here: https://github.com/mmoollllee/nuxt-starter-template
And the example: https://mmoollllee.github.io/nuxt-starter-template/
